reviews_data = [
    {"user_id": 1, "book_id": 1, "book_rating": 5, "book_review": "A stunning work that envisions a future dystopia. Orwell's '1984' is a masterpiece of political commentary."},
    {"user_id": 1, "book_id": 2, "book_rating": 4, "book_review": "Animal Farm is a classic allegory with powerful messages. It is relevant even today."},
    {"user_id": 1, "book_id": 3, "book_rating": 3, "book_review": "To the Lighthouse provides an insightful exploration of human relationships, emotions, and the passage of time."},
    {"user_id": 1, "book_id": 4, "book_rating": 4, "book_review": "Mrs Dalloway brilliantly encapsulates a single day in London, filled with rich internal monologues and streams of consciousness."},
    {"user_id": 1, "book_id": 5, "book_rating": 5, "book_review": "The Old Man and The Sea is a tale of struggle and resilience. Hemingway's prose is powerful and evocative."},
    {"user_id": 1, "book_id": 6, "book_rating": 4, "book_review": "A Farewell to Arms delivers an intense portrayal of love and war. Hemingway's writing is raw and beautiful."},
    {"user_id": 1, "book_id": 7, "book_rating": 3, "book_review": "Ulysses is challenging yet rewarding. Joyce's work requires patience, but it's a journey worth undertaking."},
    {"user_id": 1, "book_id": 8, "book_rating": 4, "book_review": "Finnegans Wake is complex and dense, but its linguistic inventiveness is a testament to Joyce's genius."},
    {"user_id": 1, "book_id": 9, "book_rating": 4, "book_review": "Wuthering Heights is a haunting tale of love and obsession. Bronte's characters are unforgettable."},
    {"user_id": 1, "book_id": 10, "book_rating": 5, "book_review": "Pride and Prejudice is an enduring classic. Austen's wit and character development are remarkable."},
    {"user_id": 1, "book_id": 11, "book_rating": 4, "book_review": "Emma is a lively comedy of manners that explores societal constraints and human nature."},
    {"user_id": 1, "book_id": 12, "book_rating": 3, "book_review": "Great Expectations is a moving coming-of-age story, filled with memorable characters and sharp social critique."},
    {"user_id": 1, "book_id": 13, "book_rating": 4, "book_review": "Oliver Twist presents a vivid picture of London's criminal underworld. Dickens' storytelling is masterful."},
    {"user_id": 1, "book_id": 14, "book_rating": 5, "book_review": "Adventures of Huckleberry Finn is both a great adventure story and a powerful social commentary."},
    {"user_id": 1, "book_id": 15, "book_rating": 4, "book_review": "The Adventures of Tom Sawyer is a delightful portrayal of boyhood along the Mississippi River."},
    {"user_id": 1, "book_id": 16, "book_rating": 5, "book_review": "To Kill a Mockingbird is a masterpiece that addresses profound themes of morality, prejudice, and the loss of innocence."},
    {"user_id": 1, "book_id": 17, "book_rating": 3, "book_review": "Go Set a Watchman presents a more complex, but perhaps less appealing, version of Atticus Finch. It's a challenging companion piece to To Kill a Mockingbird."},
    {"user_id": 1, "book_id": 18, "book_rating": 4, "book_review": "The Catcher in the Rye is a definitive work on adolescent alienation. Salinger's narrative voice is uniquely compelling."},
    {"user_id": 1, "book_id": 19, "book_rating": 4, "book_review": "Nine Stories showcases Salinger's skill in writing short fiction. His characters and dialogues are vivid and memorable."},
    {"user_id": 1, "book_id": 20, "book_rating": 4, "book_review": "Franny and Zooey is a touching exploration of spiritual crisis and familial bonds. Salinger's style is immersive and engaging."},
    
    
    {"user_id": 2, "book_id": 1, "book_rating": 5, "book_review": "Orwell's '1984' paints a chilling picture of a dystopian future. It is a powerful critique of totalitarian regimes."},
    {"user_id": 2, "book_id": 2, "book_rating": 4, "book_review": "'Animal Farm' is a brilliant allegorical novel that showcases Orwell's insight into the mechanisms of power."},
    {"user_id": 2, "book_id": 3, "book_rating": 3, "book_review": "While 'To the Lighthouse' by Virginia Woolf is an introspective look into characters' psyches, it's a slow read."},
    {"user_id": 2, "book_id": 4, "book_rating": 4, "book_review": "Woolf's 'Mrs Dalloway' is a beautiful exploration of a single day in a woman's life."},
    {"user_id": 2, "book_id": 3, "book_rating": 5, "book_review": "The Old Man and The Sea is a testament to Hemingway's talent for poignant storytelling."},
    {"user_id": 2, "book_id": 6, "book_rating": 4, "book_review": "Hemingway's 'A Farewell to Arms' is a raw and powerful narrative of love and war."},
    {"user_id": 2, "book_id": 7, "book_rating": 3, "book_review": "'Ulysses' is a difficult read, but the journey through its labyrinthine narrative structure is worthwhile."},
    {"user_id": 2, "book_id": 8, "book_rating": 4, "book_review": "Interesting work by James Joyce, although it was challenging due to its experimental style."},
    {"user_id": 2, "book_id": 9, "book_rating": 5, "book_review": "The rawness of emotions in 'Wuthering Heights' is a testament to Emily Bronte's brilliant writing."},
    {"user_id": 2, "book_id": 10, "book_rating": 5, "book_review": "Austen's 'Pride and Prejudice' provides a detailed look into society norms and is a classic romance."},
    {"user_id": 2, "book_id": 11, "book_rating": 4, "book_review": "Emma is Austen's finest work, with excellent character development and humorous dialogue."},
    {"user_id": 2, "book_id": 12, "book_rating": 3, "book_review": "Although 'Great Expectations' was tough to get into, it was overall a compelling narrative by Dickens."},
    {"user_id": 2, "book_id": 13, "book_rating": 4, "book_review": "'Oliver Twist' remains a classic with its poignant portrayal of societal injustice."},
    {"user_id": 2, "book_id": 14, "book_rating": 5, "book_review": "'Adventures of Huckleberry Finn' is a timeless classic that combines humor, adventure, and humanism."},
    {"user_id": 2, "book_id": 15, "book_rating": 4, "book_review": "Twain's 'The Adventures of Tom Sawyer' is a delightful read that captures the essence of childhood."},
    {"user_id": 2, "book_id": 16, "book_rating": 5, "book_review": "'To Kill a Mockingbird' is an enduring tale of morality and racial inequality. It's a must-read."},
    {"user_id": 2, "book_id": 17, "book_rating": 3, "book_review": "'Go Set a Watchman' is a fascinating, though controversial, follow-up to 'To Kill a Mockingbird'."},
    {"user_id": 2, "book_id": 18, "book_rating": 4, "book_review": "Salinger's 'The Catcher in the Rye' is an emotional journey through the protagonist's psyche."},
    {"user_id": 2, "book_id": 19, "book_rating": 4, "book_review": "'Nine Stories' by Salinger showcases his ability to encapsulate profound themes within simple narratives."},
    {"user_id": 2, "book_id": 20, "book_rating": 4, "book_review": "'Franny and Zooey' is a gripping exploration of religious curiosity and the dynamics of family relationships."},

    
    {"user_id": 3, "book_id": 1, "book_rating": 5, "book_review": "A stunning work that envisions a future dystopia. Orwell's '1984' is a masterpiece of political commentary."},
    {"user_id": 3, "book_id": 2, "book_rating": 4, "book_review": "Animal Farm beautifully demonstrates the corruption of revolution by its leaders. Orwell's satire remains relevant and impactful."},
    {"user_id": 3, "book_id": 3, "book_rating": 5, "book_review": "To the Lighthouse is an insightful exploration of the human mind and its relationship with the outside world. A remarkable example of Woolf's stream of consciousness style."},
    {"user_id": 3, "book_id": 4, "book_rating": 4, "book_review": "Mrs Dalloway is a beautiful and moving depiction of a day in a woman's life, a classic of modernist literature."},
    {"user_id": 3, "book_id": 5, "book_rating": 5, "book_review": "The Old Man and The Sea is an eloquent tribute to man's resilience in the face of failure. Hemingway's simple yet powerful prose is remarkable."},
    {"user_id": 3, "book_id": 6, "book_rating": 4, "book_review": "A Farewell to Arms provides a deeply affecting portrayal of love and war. Hemingway's writing is both heart-wrenching and beautiful."},
    {"user_id": 3, "book_id": 7, "book_rating": 5, "book_review": "Ulysses is a challenging but rewarding read, full of innovative stylistic choices and deep, meaningful character studies."},
    {"user_id": 3, "book_id": 8, "book_rating": 3, "book_review": "Finnegans Wake is a complex, cryptic work. Joyce's innovative use of language is both fascinating and frustrating."},
    {"user_id": 3, "book_id": 9, "book_rating": 4, "book_review": "Wuthering Heights is a compelling tale of passion and revenge. Bronte's evocative description of the moorland setting adds to the brooding atmosphere."},
    {"user_id": 3, "book_id": 10, "book_rating": 5, "book_review": "Pride and Prejudice is a delightful read. The characters, particularly the witty Elizabeth Bennet, are wonderfully realised."},
    {"user_id": 3, "book_id": 11, "book_rating": 4, "book_review": "Emma is a charming novel with a wonderfully flawed protagonist. Austen's clever use of irony and social commentary is superb."},
    {"user_id": 3, "book_id": 12, "book_rating": 5, "book_review": "Great Expectations is a classic tale of love, social mobility, and personal growth. Dickens's richly-detailed writing brings the characters to life."},
    {"user_id": 3, "book_id": 13, "book_rating": 4, "book_review": "Oliver Twist is a stark exploration of the struggle for survival in 19th century London. A powerful and moving read."},
    {"user_id": 3, "book_id": 14, "book_rating": 5, "book_review": "Adventures of Huckleberry Finn is an essential American novel, full of humor and wisdom. Twain's depiction of life along the Mississippi River is legendary."},
    {"user_id": 3, "book_id": 15, "book_rating": 4, "book_review": "The Adventures of Tom Sawyer is a fun and adventurous read, capturing the essence of childhood imagination and freedom."},
    {"user_id": 3, "book_id": 16, "book_rating": 5, "book_review": "To Kill a Mockingbird is a profound book with powerful themes of racism and innocence. An essential read for everyone."},
    {"user_id": 3, "book_id": 17, "book_rating": 3, "book_review": "Go Set a Watchman revisits the characters of To Kill a Mockingbird, offering a more complex and less idealistic view of the issues at hand."},
    {"user_id": 3, "book_id": 18, "book_rating": 5, "book_review": "The Catcher in the Rye is a classic coming-of-age story, capturing the angst and alienation of adolescence. Salinger's writing style is both authentic and compelling."},
    {"user_id": 3, "book_id": 19, "book_rating": 4, "book_review": "Nine Stories is a collection of sharp and poignant short stories. Salinger's depth of characterisation in each story is masterful."},
    {"user_id": 3, "book_id": 20, "book_rating": 4, "book_review": "Franny and Zooey is a fascinating exploration of spirituality and the human condition. Salinger's writing is introspective and illuminating."}
]
