books_data = [
    {'book_title': 'The Alchemist',
  'page_count': 208,
  'publish_date': '1988-05-01',
  'price': 14.95,
  'description': 'A philosophical book that tells the story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
  'inventory_count': 12,
  'isbn': '9780062315007',
  'author_id': '779fa00a-09d6-444e-9ce8-540e65ac5e19'},
 {'book_title': 'Pride and Prejudice',
  'page_count': 432,
  'publish_date': '1813-01-28',
  'price': 9.99,
  'description': 'The novel follows the character development of Elizabeth Bennet, the dynamic protagonist, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.',
  'inventory_count': 74,
  'isbn': '9781503290563',
  'author_id': '8283a8d6-e43b-4e48-8b4b-229e7a3f9a7f'},
 {'book_title': 'Adventures of Huckleberry Finn',
  'page_count': 366,
  'publish_date': '1884-12-10',
  'price': 8.99,
  'description': 'Direct sequel to The Adventures of Tom Sawyer. The book is noted for its colorful description of people and places along the Mississippi River.',
  'inventory_count': 81,
  'isbn': '9780486400778',
  'author_id': '78f2351f-8786-45f6-8e8e-78d3dc51e9fa'},
 {'book_title': 'Mrs. Dalloway',
  'page_count': 194,
  'publish_date': '1925-05-14',
  'price': 7.99,
  'description': "Details a day in the life of Clarissa Dalloway, a fictional high-society woman in post–First World War England. It is one of Woolf's best-known novels.",
  'inventory_count': 87,
  'isbn': '9780156628709',
  'author_id': 'a41e87a3-ed5a-432b-88e8-ac5d971f1c36'},
 {'book_title': 'Anna Karenina',
  'page_count': 864,
  'publish_date': '1877-04-01',
  'price': 12.99,
  'description': "Tolstoy's Anna Karenina tells of the doomed love affair between the sensuous and rebellious Anna and the dashing officer, Count Vronsky.",
  'inventory_count': 67,
  'isbn': '9781400079988',
  'author_id': '19730510-9a97-4ce9-a39d-506bb7ff1a8f'},
 {'book_title': 'Warrior of the Light',
  'page_count': 160,
  'publish_date': '2003-03-30',
  'price': 16.99,
  'description': 'A manual that teaches the reader, through stories and reflections, how to embrace the warrior of the light within themselves.',
  'inventory_count': 36,
  'isbn': '9780060527983',
  'author_id': '779fa00a-09d6-444e-9ce8-540e65ac5e19'},
 {'book_title': 'Emma',
  'page_count': 544,
  'publish_date': '1815-12-25',
  'price': 11.99,
  'description': 'A novel about youthful hubris and the perils of misconstrued romance, the story explores the concerns and difficulties of genteel women living in Georgian–Regency England.',
  'inventory_count': 41,
  'isbn': '9780141439587',
  'author_id': '8283a8d6-e43b-4e48-8b4b-229e7a3f9a7f'},
 {'book_title': 'Life on the Mississippi',
  'page_count': 624,
  'publish_date': '1883-01-01',
  'price': 13.95,
  'description': "A memoir of Twain's experiences as a steamboat pilot on the Mississippi River before the American Civil War, and a travel book, recounting his trip down the Mississippi River from St. Louis to New Orleans many years after the War.",
  'inventory_count': 6,
  'isbn': '9780486414263',
  'author_id': '78f2351f-8786-45f6-8e8e-78d3dc51e9fa'},
 {'book_title': 'Orlando',
  'page_count': 256,
  'publish_date': '1928-10-11',
  'price': 14.95,
  'description': "A semi-biographical novel based in part on the life of Woolf's lover Vita Sackville-West, it is generally considered one of Woolf's most accessible novels.",
  'inventory_count': 36,
  'isbn': '9780156701600',
  'author_id': 'a41e87a3-ed5a-432b-88e8-ac5d971f1c36'},
 {'book_title': 'The Death of Ivan Ilyich',
  'page_count': 86,
  'publish_date': '1886-02-01',
  'price': 10.0,
  'description': 'A novella by Leo Tolstoy, considered one of the masterpieces of his late fiction, written shortly after his religious conversion of the late 1870s.',
  'inventory_count': 29,
  'isbn': '9780486435091',
  'author_id': '19730510-9a97-4ce9-a39d-506bb7ff1a8f'}
]

# books_data = [
#     {
#         "book_title": "1984",
#         "page_count": 328,
#         "publish_date": "1949-06-08",
#         "price": 19.84,
#         "description": "A dystopian novel by English novelist George Orwell.",
#         "inventory_count": 120,
#         "isbn": "978-0451524935",
#         "author_id": 1
#     },
#     {
#         "book_title": "Animal Farm",
#         "page_count": 112,
#         "publish_date": "1945-08-17",
#         "price": 12.99,
#         "description": "A fairy story by George Orwell, portraying a revolution by farm animals against humans.",
#         "inventory_count": 100,
#         "isbn": "978-0451526342",
#         "author_id": 1
#     },
#     {
#         "book_title": "To the Lighthouse",
#         "page_count": 209,
#         "publish_date": "1927-05-05",
#         "price": 15.20,
#         "description": "The Ramsays and their eight children vacation with an assortment of scholarly and artistic houseguests by the sea.",
#         "inventory_count": 85,
#         "isbn": "978-0156907392",
#         "author_id": 2
#     },
#     {
#         "book_title": "Mrs Dalloway",
#         "page_count": 194,
#         "publish_date": "1925-05-14",
#         "price": 13.95,
#         "description": "The novel details a day in the life of Clarissa Dalloway, a fictional high-society woman in post–First World War England.",
#         "inventory_count": 75,
#         "isbn": "978-0156628709",
#         "author_id": 2
#     },
#     {
#         "book_title": "The Old Man and The Sea",
#         "page_count": 128,
#         "publish_date": "1952-09-01",
#         "price": 15,
#         "description": "The story of an old Cuban fisherman and his supreme ordeal: a relentless, agonizing battle with a giant marlin far out in the Gulf Stream.",
#         "inventory_count": 100,
#         "isbn": "978-0684801223",
#         "author_id": 3
#     },
#     {
#         "book_title": "A Farewell to Arms",
#         "page_count": 332,
#         "publish_date": "1929-10-28",
#         "price": 17,
#         "description": "A novel written by Ernest Hemingway set during the Italian campaign of World War I.",
#         "inventory_count": 80,
#         "isbn": "978-0684801469",
#         "author_id": 3
#     },
#     {
#         "book_title": "Ulysses",
#         "page_count": 730,
#         "publish_date": "1922-02-02",
#         "price": 24.95,
#         "description": "The novel imitates registers of centuries of English literature and is highly allusive.",
#         "inventory_count": 60,
#         "isbn": "978-0679722762",
#         "author_id": 4
#     },
#     {
#         "book_title": "Finnegans Wake",
#         "page_count": 628,
#         "publish_date": "1939-05-04",
#         "price": 22.95,
#         "description": "A work of fiction by Irish writer James Joyce, significant for its experimental style.",
#         "inventory_count": 40,
#         "isbn": "978-0141181264",
#         "author_id": 4
#     },
#     {
#         "book_title": "Wuthering Heights",
#         "page_count": 464,
#         "publish_date": "1847-12-01",
#         "price": 14.99,
#         "description": "A novel by Emily Bronte, it follows the life of Heathcliff, a mysterious gypsy-like person.",
#         "inventory_count": 50,
#         "isbn": "978-0553212587",
#         "author_id": 5
#     },
#     {
#         "book_title": "Pride and Prejudice",
#         "page_count": 279,
#         "publish_date": "1813-01-28",
#         "price": 9.99,
#         "description": "A romantic novel of manners written by Jane Austen.",
#         "inventory_count": 120,
#         "isbn": "978-1503290563",
#         "author_id": 6
#     },
#         {
#         "book_title": "Emma",
#         "page_count": 368,
#         "publish_date": "1815-12-23",
#         "price": 12.99,
#         "description": "A novel about youthful hubris and romantic misunderstandings. It is set in the fictional country village of Highbury and the surrounding estates of Hartfield, Randalls, and Donwell Abbey.",
#         "inventory_count": 70,
#         "isbn": "978-0141439587",
#         "author_id": 6
#     },
#     {
#         "book_title": "Great Expectations",
#         "page_count": 544,
#         "publish_date": "1861-08-01",
#         "price": 10.99,
#         "description": "The novel, written by Charles Dickens, is a bildungsroman, a coming-of-age story, and it is a classic work of Victorian literature.",
#         "inventory_count": 85,
#         "isbn": "978-0141439563",
#         "author_id": 7
#     },
#     {
#         "book_title": "Oliver Twist",
#         "page_count": 368,
#         "publish_date": "1838-02-01",
#         "price": 11.99,
#         "description": "The novel tells the story of an orphan boy and his experiences with crime and hardship in London.",
#         "inventory_count": 65,
#         "isbn": "978-0486424538",
#         "author_id": 7
#     },
#     {
#         "book_title": "Adventures of Huckleberry Finn",
#         "page_count": 224,
#         "publish_date": "1884-12-10",
#         "price": 9.99,
#         "description": "A novel by Mark Twain, it is commonly named among the Great American Novels. The work is among the first in major American literature to be written throughout in vernacular English.",
#         "inventory_count": 90,
#         "isbn": "978-0486449900",
#         "author_id": 8
#     },
#     {
#         "book_title": "The Adventures of Tom Sawyer",
#         "page_count": 184,
#         "publish_date": "1876-06-01",
#         "price": 8.99,
#         "description": "The novel is set in the 1840s in the town of St. Petersburg, which is based on Hannibal, Missouri where Twain lived as a boy.",
#         "inventory_count": 80,
#         "isbn": "978-0486400778",
#         "author_id": 8
#     },
#     {
#         "book_title": "To Kill a Mockingbird",
#         "page_count": 281,
#         "publish_date": "1960-07-11",
#         "price": 14.99,
#         "description": "The novel is renowned for its warmth and humor, despite dealing with serious issues of rape and racial inequality.",
#         "inventory_count": 120,
#         "isbn": "978-0446310789",
#         "author_id": 9
#     },
#     {
#         "book_title": "Go Set a Watchman",
#         "page_count": 278,
#         "publish_date": "2015-07-14",
#         "price": 15.99,
#         "description": "Written in the mid-1950s, the novel was published by Harper Lee in 2015, as a follow-up to To Kill a Mockingbird.",
#         "inventory_count": 70,
#         "isbn": "978-0062409850",
#         "author_id": 9
#     },
#     {
#         "book_title": "The Catcher in the Rye",
#         "page_count": 277,
#         "publish_date": "1951-07-16",
#         "price": 8.99,
#         "description": "The novel's protagonist, Holden Caulfield, has become an icon for teenage rebellion and angst.",
#         "inventory_count": 95,
#         "isbn": "978-7543321724",
#         "author_id": 10
#     },
#     {
#         "book_title": "Nine Stories",
#         "page_count": 198,
#         "publish_date": "1953-04-06",
#         "price": 10.99,
#         "description": "A collection of short stories by J.D. Salinger. It includes two of his most famous short stories, 'A Perfect Day for Bananafish' and 'For Esmé – with Love and Squalor'.",
#         "inventory_count": 75,
#         "isbn": "978-0316769495",
#         "author_id": 10
#     },
#     {
#         "book_title": "Franny and Zooey",
#         "page_count": 201,
#         "publish_date": "1961-09-12",
#         "price": 12.99,
#         "description": "The book comprises his short story 'Franny' and novella 'Zooey', both of which revolve around the two youngest members of the Glass family.",
#         "inventory_count": 65,
#         "isbn": "978-0316769495",
#         "author_id": 10
#     }
# ]
