category_data = [
    {"category": "Dystopian"},
    {"category": "Political Fiction"},
    {"category": "Science Fiction"},
    {"category": "Political Satire"},
    {"category": "Allegory"},
    {"category": "Fable"},
    {"category": "Modernism"},
    {"category": "Psychological Fiction"},
    {"category": "Feminist Literature"},
    {"category": "Stream of Consciousness"},
    {"category": "Adventure"},
    {"category": "Classic"},
    {"category": "Fiction"},
    {"category": "War Fiction"},
    {"category": "Romantic Tragedy"},
    {"category": "Historical Fiction"},
    {"category": "Epic"},
    {"category": "Avant-Garde"},
    {"category": "Experimental Literature"},
    {"category": "Gothic Fiction"},
    {"category": "Romance"},
    {"category": "Tragedy"},
    {"category": "Comedy of Manners"},
    {"category": "Coming-of-Age"},
    {"category": "Social Criticism"},
    {"category": "Crime"},
    {"category": "Satire"},
    {"category": "Humor"},
    {"category": "Racial Injustice"},
    {"category": "Southern Gothic"},
    {"category": "Short Stories"},
    {"category": "Postmodern Literature"},
    {"category": "Existential Crisis"},
    {"category": "Spiritual Journey"}
]