users_data = [
    { "user_name": "fuckinadmin", "password": "admin", "email": "admin@admin.com", "first_name": "Juicy", "last_name": "Jay", "role": "admin" },
    # { "user_name": "user1", "password": "admin", "email": "user1@admin.com", "first_name": "John", "last_name": "Doe", "role": "user" },
    # { "user_name": "user2", "password": "admin", "email": "user2@admin.com", "first_name": "Jane", "last_name": "Doe", "role": "user" },
    # { "user_name": "user3", "password": "admin", "email": "user3@admin.com", "first_name": "James", "last_name": "Doe", "role": "user" },
    { "user_name": "booklover1", "password": "admin", "email": "booklover1@admin.com", "first_name": "John", "last_name": "Doe", "role": "user" },
    { "user_name": "reader123", "password": "admin", "email": "reader123@admin.com", "first_name": "Jane", "last_name": "Smith", "role": "user" },
    { "user_name": "bibliophile", "password": "admin", "email": "bibliophile22@admin.com", "first_name": "Michael", "last_name": "Johnson", "role": "user" },
    { "user_name": "bookworm", "password": "admin", "email": "bookworm4eva@admin.com", "first_name": "Emily", "last_name": "Davis", "role": "user" },
    { "user_name": "avidreader7", "password": "admin", "email": "avidreader7@admin.com", "first_name": "David", "last_name": "Anderson", "role": "user" },
    { "user_name": "bookishgal", "password": "admin", "email": "bookishgal@admin.com", "first_name": "Sarah", "last_name": "Wilson", "role": "user" },
    { "user_name": "litlover88", "password": "admin", "email": "litlover88@admin.com", "first_name": "Robert", "last_name": "Brown", "role": "user" },
    { "user_name": "jenreads", "password": "admin", "email": "jenniferreads@admin.com", "first_name": "Jennifer", "last_name": "Lee", "role": "user" },
    { "user_name": "iambook", "password": "admin", "email": "williambookworm@admin.com", "first_name": "William", "last_name": "Taylor", "role": "user" },
    { "user_name": "lovesbooks", "password": "admin", "email": "lauralovesbooks@admin.com", "first_name": "Laura", "last_name": "Miller", "role": "user" },
]